# Introduction to tensorflow

In [45]:
import tensorflow as tf

In [46]:
tf.InteractiveSession()
# Keeps a default session open in ipython.


In [55]:
x=tf.constant([1,2,3,4],shape=[2,2])
print(x)  

Tensor("Const_45:0", shape=(2, 2), dtype=int32)


In [56]:
print tf.Session().run(x)
# or->
# with import tf.Session() as sess:
#        sess.run(x)       
print x.eval() # shorthand for sess.run(output)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [64]:
a=tf.constant([5,6,7,8],shape=[2,2])
b=tf.constant([[5,6],[7,8]])
c=tf.constant([[[5],[6]],[[7],[8]]])    # 2x2x1 matrix
import numpy as np
f=tf.constant(np.random.rand(3,3))

print(c.eval())
print(f.eval())

[[[5]
  [6]]

 [[7]
  [8]]]
[[ 0.95874802  0.56495904  0.77395034]
 [ 0.15639488  0.33583109  0.38151375]
 [ 0.13865251  0.66157033  0.00474448]]


In [61]:
examples=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
weights=tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
bias=tf.constant([1.0,2.0])
output=tf.matmul(examples,weights)+bias
print("examples->")
print(examples.eval())
print("wights->")
print(weights.eval())
print("bias->")
print(bias.eval())
print("output->")
print output.eval()
    

examples->
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
wights->
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
bias->
[ 1.  2.]
output->
[[ 23.  30.]
 [ 50.  66.]]


In [67]:
x=tf.Variable([2.,5.,6.,7.],name="rand")
tf.initialize_all_variables().run()  # all variables must be initialized
print x.eval()
assign_op=x.assign(tf.constant([1.,2.,3.,5.]))
#  during assignment, new value's dimension must be same as original dimension 
assign_op.op.run()
print x.eval()
#see more- http://stackoverflow.com/questions/34220532/how-to-assign-value-to-a-tensorflow-variable

[ 2.  5.  6.  7.]
[ 1.  2.  3.  5.]


In [35]:
a = tf.zeros((2,2)); b = tf.ones((2,2))
print(a.eval())
print(b.eval())
x=tf.reduce_sum(b, reduction_indices=1)
print(x.eval())


[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[ 2.  2.]


In [38]:
print(a.get_shape())
print(x.get_shape())

(2, 2)
(2, 2)
(2,)


In [40]:
re_a=tf.reshape(a, (1, 4))
print(re_a.eval())


[[ 0.  0.  0.  0.]]


In [68]:
state = tf.Variable(0, name="counter")
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)
tf.initialize_all_variables().run()
print state.eval()
for _ in range(3):
    update.eval()
    print state.eval()


0
1
2
3


In [71]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)
intermed = tf.add(input2, input3)
mul = tf.mul(input1, intermed)
with tf.Session() as sess:
    result = sess.run([mul, intermed])
print(result)


[21.0, 7.0]


In above cell, sess.run() "fetches" multiple variable values.
Multiple values can't be "eval()" in one go. Hence we use sess.run() instead of eval() here 


In [73]:
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a)
print(ta.eval())

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


###  tf.placeholder variables (dummy nodes that provide entry points for data to computational graph). 

### A feed_dict is a python dictionary mapping from tf. placeholder vars (or their names) to data (numpy arrays,lists, etc.).


In [74]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.mul(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))


[array([ 14.], dtype=float32)]


### tf.variable_scope() provides simple name-spacing to avoid clashes.

### tf.get_variable() creates/accesses variables from within a variable scope.


In [76]:
with tf.variable_scope("foo"):
    with tf.variable_scope("bar"):
        v = tf.get_variable("v", [1])
assert v.name == "foo/bar/v:0"
